version: '3.8'
services:
  myFoodApi:
    container_name: myFoodModular
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=myFood_db;Port=5432;Database=myFood;User Id=postgres;Password=${POSTGRES_PASSWORD};Include Error Detail=true
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__key=${JWTKEY}
      - Twilio__AccountSID=${TWILIOACCOUNTSID}
      - Twilio__AuthToken=${TWILIOAUTHTOKEN}
      - Twilio__TwilioPhoneNumber=${TWILIOPHONENUMBER}
      - WhatsApp__AccessToken=${WHATSAPPACCESSTOKEN}
      - WhatsApp__PhoneNumberId=${WHATSAPPPHONENUMBERID}
      - Email__Password=${EMAILPASSWORD}
      - AwsS3__AccessKey=${AWSS3ACCESSKEY}
      - AwsS3__SecretKey=${AWSS3SECRETKEY}
      
      
    depends_on:
      - myFood_db
        
    
  myFood_db:
    container_name: myFood_db
    env_file:
      - .env
    ports:
      - "5462:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=myFood
      - POSTGRES_HOST_AUTH_METHOD=md5
    restart: always
    volumes:
      - myFood_db:/var/lib/postgresql/data/
  
  
  myFood_nginx:
    container_name: myFood_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - webroot:/var/www/html

    depends_on:
      - myFoodApi

